### ISSUE TITLE
Create a uStreamer Debian release

### ISSUE THREAD

**Issue by jdeanwallace** [tiny-pilot/ustreamer-debian#4]
Related https://github.com/tiny-pilot/tinypilot/issues/1353
Dependent on https://github.com/tiny-pilot/ustreamer-debian/issues/3

Manually attach the latest uStreamer Debian package CI artifact as a GitHub release asset.

**Comment by jdeanwallace** [comment]
@mtlynch - This task has now been unblock after merging https://github.com/tiny-pilot/ustreamer-debian/pull/6

You can find the latest uStreamer Debian package [artifacts here](https://app.circleci.com/pipelines/github/tiny-pilot/ustreamer-debian/32/workflows/9d84b87f-1109-4fc8-bc5c-47876d2b571e/jobs/99/artifacts).

**Comment by mtlynch** [comment]
Release is now cut: https://github.com/tiny-pilot/ustreamer-debian/releases/tag/5.38-20230524143200
